fix: improve logging
- In case of some console errors, the Value field is empty,
but Description gets populated. Check that appropriately and log it.
- In case of exceptions, cancel the context so that it does not remain
stuck.

This gives a better message:

TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
http://localhost:34895/wasm_exec.js:482:38 Uncaught (in promise)
TypeError: Cannot read property 'exports' of undefined
    at global.Go.run (http://localhost:34895/wasm_exec.js:483:39)
    at http://localhost:34895/:103:13
[wasmbrowsertest]: 2020/02/29 13:12:58 main.go:150: context canceled

instead of getting stuck at

TypeError: Cannot read property 'exports' of undefined
    at global.Go.run (http://localhost:29639/wasm_exec.js:483:39)
    at http://localhost:29639/:103:13